#!/bin/sh

# user_name@host_name/your/path/
#COE='user_name@host_name/~'
#CIS='user_name@host_name/~'
#CC='user_name@host_name/~/www'

# short cut
case ${1} in
coe | COE)
  HOST=$COE
  ;;
cis | CIS)
  HOST=$CIS
  ;;
cc | CC)
  HOST=$CC
  ;;
*)
  HOST=${1}
  ;;
esac

# run vim
vim scp://$HOST/${2}
